#!/bin/bash

echo "============================================================"
echo "  TheRock Issue Analysis Dashboard - Quick Setup"
echo "============================================================"
echo ""
echo "The dashboard needs a GitHub token to fetch issues."
echo "Without it, GitHub API requests will timeout or fail."
echo ""
echo "📋 Steps to fix:"
echo ""
echo "1. Get a GitHub Personal Access Token:"
echo "   - Go to: https://github.com/settings/tokens"
echo "   - Click 'Generate new token (classic)'"
echo "   - Give it a name like 'TheRock Dashboard'"
echo "   - Select scopes: 'repo' (full control of private repositories)"
echo "   - Click 'Generate token' and COPY the token"
echo ""
echo "2. Create .env file:"
echo "   cd /home/safaizal/projects/TheRock/dashboards/backend"
echo "   cp env.example .env"
echo ""
echo "3. Edit .env and add your token:"
echo "   GITHUB_TOKEN=ghp_your_token_here"
echo ""
echo "4. Restart the server"
echo ""
echo "============================================================"
echo ""
echo "Quick commands:"
echo ""
echo "  # Copy example config"
echo "  cp /home/safaizal/projects/TheRock/dashboards/backend/env.example /home/safaizal/projects/TheRock/dashboards/backend/.env"
echo ""
echo "  # Edit the file (add your GitHub token)"
echo "  nano /home/safaizal/projects/TheRock/dashboards/backend/.env"
echo ""
echo "  # Restart server"
echo "  pkill -f 'python3 app.py' && cd /home/safaizal/projects/TheRock/dashboards/backend && python3 app.py &"
echo ""
echo "============================================================"




